version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: wecon-postgres
    environment:
      POSTGRES_DB: wecon_masawat
      POSTGRES_USER: wecon_user
      POSTGRES_PASSWORD: wecon_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wecon-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: wecon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wecon-network
    restart: unless-stopped

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wecon-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://wecon_user:wecon_password@postgres:5432/wecon_masawat
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=your-super-secret-key-change-this-in-production
      - NEXTAUTH_URL=http://localhost:3000
      - JWT_SECRET=your-jwt-secret-change-this-in-production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - wecon-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  # MinIO for file storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: wecon-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - wecon-network
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: wecon-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - wecon-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  wecon-network:
    driver: bridge
